<a href="https://colab.research.google.com/github/deshmukh2409/Artificial_Intelligence_Lab_SE_A_12/blob/master/Ep_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# Define the coefficient matrix A
A = np.array([
    [2, 3],
    [4, 5]
])

# Define the constants vector B
B = np.array([
    [10],
    [20]
])

print("Coefficient Matrix A:")
print(A)
print("\nConstants Vector B:")
print(B)

# Solve the system of linear equations Ax = B
solution = np.linalg.solve(A, B)

print("\nSolution (x, y):")
print(solution)

# You can access x and y individually
x = solution[0][0]
y = solution[1][0]

print(f"\nx = {x:.2f}")
print(f"y = {y:.2f}")

Coefficient Matrix A:
[[2 3]
 [4 5]]

Constants Vector B:
[[10]
 [20]]

Solution (x, y):
[[5.]
 [0.]]

x = 5.00
y = 0.00


In [2]:
import numpy as np

# Create a new non-singular 3x3 square matrix
new_matrix = np.array([
    [1, 2, 0],
    [0, 1, 0],
    [0, 0, 1]
])

print("New 3x3 Matrix:")
print(new_matrix)

# Compute the determinant of the new matrix
new_determinant = np.linalg.det(new_matrix)
print(f"\nDeterminant of the new matrix: {new_determinant}")

# Compute the inverse of the new matrix
if new_determinant != 0:
    inverse_matrix = np.linalg.inv(new_matrix)
    print("\nInverse of the new matrix:")
    print(inverse_matrix)
else:
    print("\nThis matrix is also singular and does not have an inverse.")

New 3x3 Matrix:
[[1 2 0]
 [0 1 0]
 [0 0 1]]

Determinant of the new matrix: 1.0

Inverse of the new matrix:
[[ 1. -2.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [1]:
import numpy as np

# Create a 3x3 square matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Original 3x3 Matrix:")
print(matrix)

# Compute the determinant of the matrix
determinant = np.linalg.det(matrix)

print(f"\nDeterminant of the matrix: {determinant}")

Original 3x3 Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of the matrix: 0.0
