<a href="https://colab.research.google.com/github/deshmukh2409/Artificial_Intelligence_Lab_SE_A_12/blob/main/Exp_3_(DSL).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

# Define the coefficient matrix A
A = np.array([[2, 3], [4, 5]])

# Define the constant vector B
B = np.array([10, 20])

# Solve the system of equations Ax = B for x
solution = np.linalg.solve(A, B)

print("Solution to the system of equations:")
print(f"x = {solution[0]:.2f}")
print(f"y = {solution[1]:.2f}")

Solution to the system of equations:
x = 5.00
y = 0.00


In [3]:
# Compute the inverse of the matrix
inverse_matrix = np.linalg.inv(matrix)

print("\nInverse of the matrix:")
print(inverse_matrix)


Inverse of the matrix:
[[ 0.17391304  0.         -0.04347826]
 [-0.39130435 -0.          0.34782609]
 [-0.2173913   1.         -0.69565217]]


In [1]:
import numpy as np

# Create a 3x3 square matrix
matrix = np.random.randint(0, 10, size=(3, 3))
print("Generated 3x3 Matrix:")
print(matrix)

Generated 3x3 Matrix:
[[8 1 0]
 [8 3 1]
 [9 4 0]]


In [2]:
# Compute the determinant of the matrix
determinant = np.linalg.det(matrix)

print(f"\nDeterminant of the matrix: {determinant}")


Determinant of the matrix: -23.0
